<?php
// db.php - PDO connection + simple auto-migration
require_once __DIR__ . '/config.php';

function db() : PDO {
    static $pdo = null;
    $port = AZURE_DB_PORT ?? 5432;
    if ($pdo === null) {
        $dsn = 'pgsql:host=' . DB_HOST . ';port=' . $port . ';dbname=' . DB_NAME;
        $pdo = new PDO($dsn, DB_USER, DB_PASS, [
            PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_ASSOC,
        ]);
        ensure_schema($pdo);
    }
    return $pdo;
}

// function ensure_schema(PDO $pdo) {
//     $pdo->exec("CREATE TABLE IF NOT EXISTS auth_users (
//         id INT AUTO_INCREMENT PRIMARY KEY,
//         name VARCHAR(255) NOT NULL,
//         email VARCHAR(255) NOT NULL UNIQUE,
//         password_hash VARCHAR(255) NOT NULL,
//         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
//     ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;");
// }

function ensure_schema(PDO $pdo) {
    $pdo->exec("
        CREATE TABLE IF NOT EXISTS auth_users (
            id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name         TEXT        NOT NULL,
            email        TEXT        NOT NULL UNIQUE,
            password_hash TEXT       NOT NULL,
            created_at   TIMESTAMPTZ NOT NULL DEFAULT NOW()
        );
    ");
}
